.TH "Node" 3 "Mon Sep 3 2018" "Version 0.0.2" "GraphPass" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Node \- Holds graph level values for each graph that has been filtered\&.  

.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char * \fBabbrev\fP"
.br
.ti -1c
.RI "igraph_real_t \fBval\fP"
.br
.ti -1c
.RI "struct \fBNode\fP * \fBnext\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Holds graph level values for each graph that has been filtered\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for GraphPass from the source code\&.
