.TH "headers/quickrun.h" 3 "Fri Mar 16 2018" "Version 0.0.2" "Graphpass" \" -*- nroff -*-
.ad l
.nh
.SH NAME
headers/quickrun.h \- produces a lightweight vizualization for a graph\&.  

.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBquickrunGraph\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
produces a lightweight vizualization for a graph\&. 

The quickrun utilty is intended for producing generic vizualisations for network graphs, relatively quickly using basic algorithms\&. \fBNode\fP sizes are produced using basic degree\&. \fBNode\fP (rgb) colours are delineated using walktrap modularity\&. \fBNode\fP positions are 2d and set using the Fruchterman-Rheingold algorithm, which emphasizes the spacing between nodes\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for Graphpass from the source code\&.
