.TH "RankNode" 3 "Mon Sep 3 2018" "Version 0.0.2" "GraphPass" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RankNode \- unimplemented struct for holding the top 20 rankids for the graph\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <graphpass\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBrankids\fP [20]"
.br
.ti -1c
.RI "struct \fBRankNode\fP * \fBnext\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
unimplemented struct for holding the top 20 rankids for the graph\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for GraphPass from the source code\&.
