.TH "src/graphpass.c" 3 "Fri Mar 16 2018" "Version 0.0.2" "Graphpass" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/graphpass.c \- The main file for GraphPass\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'igraph\&.h'\fP
.br
\fC#include 'graphpass\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fB_GNU_SOURCE\fP"
.br
.ti -1c
.RI "#define \fBASSETS_PATH\fP   'assets/'"
.br
.ti -1c
.RI "#define \fBMAX_METHODS\fP   9"
.br
.ti -1c
.RI "#define \fBMAX_FILESIZE\fP   100"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char *argv[])"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "bool \fBSAVE\fP = true"
.br
.ti -1c
.RI "bool \fBGFORMAT\fP = false"
.br
.ti -1c
.RI "bool \fBREPORT\fP = false"
.br
.ti -1c
.RI "bool \fBQUICKRUN\fP = false"
.br
.ti -1c
.RI "int \fBverbose_flag\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
The main file for GraphPass\&. 

Copyright [2018] [Ryan Deschamps]
.PP
Licensed under the Apache License, Version 2\&.0 (the 'License'); you may not use this file except in compliance with the License\&. You may obtain a copy of the License at
.PP
http://www.apache.org/licenses/LICENSE-2.0
.PP
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an 'AS IS' BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied\&. See the License for the specific language governing permissions and limitations under the License\&. Graphpass accepts a file, a percentage and a series of characters that represent methods of filtering a network graph, and outputs new graph files with the filtered graphs and optionally, a report showing how those filters affected the graph 
.SH "Author"
.PP 
Generated automatically by Doxygen for Graphpass from the source code\&.
