.TH "headers/io.h" 3 "Fri Mar 16 2018" "Version 0.0.2" "Graphpass" \" -*- nroff -*-
.ad l
.nh
.SH NAME
headers/io.h \- Basic input-output utilities (loading and writing graphs)  

.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBstrip_ext\fP (char *fname)"
.br
.ti -1c
.RI "int \fBload_graph\fP (char *filename)"
.br
.ti -1c
.RI "int \fBwrite_graph\fP (igraph_t *graph, char *attr)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Basic input-output utilities (loading and writing graphs) 


.SH "Author"
.PP 
Generated automatically by Doxygen for Graphpass from the source code\&.
