.TH "headers/rnd.h" 3 "Fri Mar 16 2018" "Version 0.0.2" "Graphpass" \" -*- nroff -*-
.ad l
.nh
.SH NAME
headers/rnd.h \- utilities for random number generation  

.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBshuffle\fP (int *array, int n)"
.br
.in -1c
.SH "Detailed Description"
.PP 
utilities for random number generation 


.SH "Function Documentation"
.PP 
.SS "int shuffle (int * array, int n)"
shuffle an array 
.SH "Author"
.PP 
Generated automatically by Doxygen for Graphpass from the source code\&.
