.TH "UNITY_STORAGE_T" 3 "Fri Mar 16 2018" "Version 0.0.2" "Graphpass" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UNITY_STORAGE_T
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "const char * \fBTestFile\fP"
.br
.ti -1c
.RI "const char * \fBCurrentTestName\fP"
.br
.ti -1c
.RI "const char * \fBCurrentDetail1\fP"
.br
.ti -1c
.RI "const char * \fBCurrentDetail2\fP"
.br
.ti -1c
.RI "UNITY_LINE_TYPE \fBCurrentTestLineNumber\fP"
.br
.ti -1c
.RI "UNITY_COUNTER_TYPE \fBNumberOfTests\fP"
.br
.ti -1c
.RI "UNITY_COUNTER_TYPE \fBTestFailures\fP"
.br
.ti -1c
.RI "UNITY_COUNTER_TYPE \fBTestIgnores\fP"
.br
.ti -1c
.RI "UNITY_COUNTER_TYPE \fBCurrentTestFailed\fP"
.br
.ti -1c
.RI "UNITY_COUNTER_TYPE \fBCurrentTestIgnored\fP"
.br
.ti -1c
.RI "jmp_buf \fBAbortFrame\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Graphpass from the source code\&.
